// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cdf53_time_lift
NumericMatrix cdf53_time_lift(NumericMatrix X, int levels, bool forward);
RcppExport SEXP _fmrilatent_cdf53_time_lift(SEXP XSEXP, SEXP levelsSEXP, SEXP forwardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< bool >::type forward(forwardSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf53_time_lift(X, levels, forward));
    return rcpp_result_gen;
END_RCPP
}
// active_pencil_wavelet
NumericVector active_pencil_wavelet(NumericVector data_voxels, IntegerMatrix coords, IntegerVector dims, int levels, bool forward);
RcppExport SEXP _fmrilatent_active_pencil_wavelet(SEXP data_voxelsSEXP, SEXP coordsSEXP, SEXP dimsSEXP, SEXP levelsSEXP, SEXP forwardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data_voxels(data_voxelsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< bool >::type forward(forwardSEXP);
    rcpp_result_gen = Rcpp::wrap(active_pencil_wavelet(data_voxels, coords, dims, levels, forward));
    return rcpp_result_gen;
END_RCPP
}
// get_morton_ordered_indices_rcpp
IntegerVector get_morton_ordered_indices_rcpp(LogicalVector mask);
RcppExport SEXP _fmrilatent_get_morton_ordered_indices_rcpp(SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(get_morton_ordered_indices_rcpp(mask));
    return rcpp_result_gen;
END_RCPP
}
// precompute_haar_scalings_rcpp
List precompute_haar_scalings_rcpp(LogicalVector mask, int levels);
RcppExport SEXP _fmrilatent_precompute_haar_scalings_rcpp(SEXP maskSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_haar_scalings_rcpp(mask, levels));
    return rcpp_result_gen;
END_RCPP
}
// forward_lift_rcpp
List forward_lift_rcpp(NumericVector data_morton, LogicalVector mask_flat_morton, IntegerVector mask_dims, int levels, List scalings);
RcppExport SEXP _fmrilatent_forward_lift_rcpp(SEXP data_mortonSEXP, SEXP mask_flat_mortonSEXP, SEXP mask_dimsSEXP, SEXP levelsSEXP, SEXP scalingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data_morton(data_mortonSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type mask_flat_morton(mask_flat_mortonSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_dims(mask_dimsSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< List >::type scalings(scalingsSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_lift_rcpp(data_morton, mask_flat_morton, mask_dims, levels, scalings));
    return rcpp_result_gen;
END_RCPP
}
// inverse_lift_rcpp
NumericVector inverse_lift_rcpp(double root_coeff, List detail_vecs, LogicalVector mask_flat_morton, IntegerVector mask_dims, int levels, List scalings);
RcppExport SEXP _fmrilatent_inverse_lift_rcpp(SEXP root_coeffSEXP, SEXP detail_vecsSEXP, SEXP mask_flat_mortonSEXP, SEXP mask_dimsSEXP, SEXP levelsSEXP, SEXP scalingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type root_coeff(root_coeffSEXP);
    Rcpp::traits::input_parameter< List >::type detail_vecs(detail_vecsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type mask_flat_morton(mask_flat_mortonSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_dims(mask_dimsSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< List >::type scalings(scalingsSEXP);
    rcpp_result_gen = Rcpp::wrap(inverse_lift_rcpp(root_coeff, detail_vecs, mask_flat_morton, mask_dims, levels, scalings));
    return rcpp_result_gen;
END_RCPP
}
// get_valid_finest_blocks_rcpp
IntegerVector get_valid_finest_blocks_rcpp(LogicalVector mask);
RcppExport SEXP _fmrilatent_get_valid_finest_blocks_rcpp(SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(get_valid_finest_blocks_rcpp(mask));
    return rcpp_result_gen;
END_RCPP
}
// hrbf_atoms_rcpp
Eigen::SparseMatrix<double> hrbf_atoms_rcpp(const Eigen::Map<Eigen::MatrixXd> mask_xyz_world, const Eigen::Map<Eigen::MatrixXd> centres_xyz_world, const Eigen::Map<Eigen::VectorXd> sigma_vec_mm, std::string kernel_type, double value_threshold);
RcppExport SEXP _fmrilatent_hrbf_atoms_rcpp(SEXP mask_xyz_worldSEXP, SEXP centres_xyz_worldSEXP, SEXP sigma_vec_mmSEXP, SEXP kernel_typeSEXP, SEXP value_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type mask_xyz_world(mask_xyz_worldSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type centres_xyz_world(centres_xyz_worldSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type sigma_vec_mm(sigma_vec_mmSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel_type(kernel_typeSEXP);
    Rcpp::traits::input_parameter< double >::type value_threshold(value_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(hrbf_atoms_rcpp(mask_xyz_world, centres_xyz_world, sigma_vec_mm, kernel_type, value_threshold));
    return rcpp_result_gen;
END_RCPP
}
// generate_dpss_basis_rcpp
Eigen::MatrixXd generate_dpss_basis_rcpp(const int n, const double NW, int k);
RcppExport SEXP _fmrilatent_generate_dpss_basis_rcpp(SEXP nSEXP, SEXP NWSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type NW(NWSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_dpss_basis_rcpp(n, NW, k));
    return rcpp_result_gen;
END_RCPP
}
// generate_dpss_tridiag_rcpp
Eigen::MatrixXd generate_dpss_tridiag_rcpp(const int n, const double NW, int k);
RcppExport SEXP _fmrilatent_generate_dpss_tridiag_rcpp(SEXP nSEXP, SEXP NWSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type NW(NWSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_dpss_tridiag_rcpp(n, NW, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmrilatent_cdf53_time_lift", (DL_FUNC) &_fmrilatent_cdf53_time_lift, 3},
    {"_fmrilatent_active_pencil_wavelet", (DL_FUNC) &_fmrilatent_active_pencil_wavelet, 5},
    {"_fmrilatent_get_morton_ordered_indices_rcpp", (DL_FUNC) &_fmrilatent_get_morton_ordered_indices_rcpp, 1},
    {"_fmrilatent_precompute_haar_scalings_rcpp", (DL_FUNC) &_fmrilatent_precompute_haar_scalings_rcpp, 2},
    {"_fmrilatent_forward_lift_rcpp", (DL_FUNC) &_fmrilatent_forward_lift_rcpp, 5},
    {"_fmrilatent_inverse_lift_rcpp", (DL_FUNC) &_fmrilatent_inverse_lift_rcpp, 6},
    {"_fmrilatent_get_valid_finest_blocks_rcpp", (DL_FUNC) &_fmrilatent_get_valid_finest_blocks_rcpp, 1},
    {"_fmrilatent_hrbf_atoms_rcpp", (DL_FUNC) &_fmrilatent_hrbf_atoms_rcpp, 5},
    {"_fmrilatent_generate_dpss_basis_rcpp", (DL_FUNC) &_fmrilatent_generate_dpss_basis_rcpp, 3},
    {"_fmrilatent_generate_dpss_tridiag_rcpp", (DL_FUNC) &_fmrilatent_generate_dpss_tridiag_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmrilatent(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
