# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdf53_time_lift <- function(X, levels, forward) {
    .Call(`_fmrilatent_cdf53_time_lift`, X, levels, forward)
}

active_pencil_wavelet <- function(data_voxels, coords, dims, levels, forward) {
    .Call(`_fmrilatent_active_pencil_wavelet`, data_voxels, coords, dims, levels, forward)
}

get_morton_ordered_indices_rcpp <- function(mask) {
    .Call(`_fmrilatent_get_morton_ordered_indices_rcpp`, mask)
}

precompute_haar_scalings_rcpp <- function(mask, levels) {
    .Call(`_fmrilatent_precompute_haar_scalings_rcpp`, mask, levels)
}

forward_lift_rcpp <- function(data_morton, mask_flat_morton, mask_dims, levels, scalings) {
    .Call(`_fmrilatent_forward_lift_rcpp`, data_morton, mask_flat_morton, mask_dims, levels, scalings)
}

inverse_lift_rcpp <- function(root_coeff, detail_vecs, mask_flat_morton, mask_dims, levels, scalings) {
    .Call(`_fmrilatent_inverse_lift_rcpp`, root_coeff, detail_vecs, mask_flat_morton, mask_dims, levels, scalings)
}

get_valid_finest_blocks_rcpp <- function(mask) {
    .Call(`_fmrilatent_get_valid_finest_blocks_rcpp`, mask)
}

hrbf_atoms_rcpp <- function(mask_xyz_world, centres_xyz_world, sigma_vec_mm, kernel_type, value_threshold = 1e-8) {
    .Call(`_fmrilatent_hrbf_atoms_rcpp`, mask_xyz_world, centres_xyz_world, sigma_vec_mm, kernel_type, value_threshold)
}

#' Generate DPSS (Slepian) basis via dense prolate matrix eigen-decomposition
#'
#' @param n Integer length of the time series.
#' @param NW Time-bandwidth product (N * W), where W is normalized half-bandwidth (cycles per sample).
#' @param k Number of tapers to return (columns).
#' @return Matrix (n x k) with columns ordered by decreasing eigenvalue (energy concentration).
#'
#' @note
#' This implementation builds the dense prolate matrix
#'   A[i,j] = 2W (i==j) else sin(2*pi*W*(i-j)) / (pi*(i-j))
#' and computes the top-k eigenvectors. It is O(n^3) and intended as a
#' simple, dependency-light starting point; consider replacing with a
#' tridiagonal solver for very long n.
#'
#' @export
generate_dpss_basis_rcpp <- function(n, NW, k) {
    .Call(`_fmrilatent_generate_dpss_basis_rcpp`, n, NW, k)
}

#' Generate DPSS via tridiagonal prolate matrix (O(n^2))
#'
#' Uses the classic tridiagonal formulation (Percival & Walden 1993; Thomson 1982)
#' and LAPACK dstev for efficiency on long series.
#'
#' @param n Integer length of the time series.
#' @param NW Time-bandwidth product (N * W), where W is normalized half-bandwidth.
#' @param k Number of tapers to return.
#' @return Matrix (n x k) with columns ordered by decreasing eigenvalue.
#'
#' @export
generate_dpss_tridiag_rcpp <- function(n, NW, k) {
    .Call(`_fmrilatent_generate_dpss_tridiag_rcpp`, n, NW, k)
}

